### ISSUE TITLE
AttributeError: 'LaunchdJob' object has no attribute 'status'

### ISSUE THREAD

**Issue by mm-johnpeterson** [infothrill/python-launchd#3]
Following the example on the readme if I try to run
```
for job in launchd.jobs():
    print(job.label, job.pid, job.status, job.properties, job.plistfilename)
```
or narrow it down to a specific .plist
`print (launchd.LaunchdJob("com.apple.Finder").status)`

AttributeError: 'LaunchdJob' object has no attribute 'status' is thrown. I've tried with python3.7 and python2.7 and the error still pops up.

**Comment by infothrill** [comment]
It looks as if the README has an error. There is no `.status` attribute. Replacing the name of the attribute with `.laststatus` works. Looks like this needs to be changed.

**Comment by mm-johnpeterson** [comment]
That fixed it. I thought I had read through the attributes but it appears I missed that. Thank you for the help.
