### ISSUE TITLE
readPlist and writePlist no longer exist in plistlib

### ISSUE THREAD

**Issue by vesche** [infothrill/python-launchd#4]
Getting an error using read/write in `plist.py` - `AttributeError: 'plistlib' has no attribute 'writePlist'` 

I'm using Python 3.9.1

`plistlib.readPlist(...)` is now `plistlib.load(...)` and `plistlib.writePlist(...)` is now `plistlib.dump(...)`

Apparently writePlist / readPlist were depreciated in 3.4 and now they don't exist at all: https://docs.python.org/3.7/library/plistlib.html

**Comment by cvpe** [comment]
Ok, missing line

from pathlib import Path
